#this file is used to configure the Nginx server for serving the React frontend and forwarding API requests to the backend service.s

server {
    listen 80;

    server_name localhost;

    # Serve the React production build
    #For requests that aren't API requests, serve the React application.
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Forward user-related API requests to the backend
    #If a request comes to Nginx whose path starts with /users/, forward that request to the backend service on port 5000.
    location /users/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Forward job and application API requests to the backend
    location /api/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}