/*we are importing bcrypt which is used to store and 
verify passwords and hashed passwords*/
const bcrypt = require("bcrypt");


/*heree we are importing package for  jwt which is a authentication token
 generated by server provided for the client for future subsequent requests
 afteer login*/
const jwt = require("jsonwebtoken");


/*here we are importing the User model from the models folder which will be 
used to interact with the users collection in the MongoDB database*/
const User = require("../models/User");


/*here we are importing the mongoose for mongo db functions */
const mongoose = require("mongoose");


/*we are initialising the first ID as 1 one to generate auot IDs we will 
create function for it */
/*let nextId = 1; wwe are not using this anymore as we are using MongoDB 
which will generate unique IDs for us automatically*/

async function registerUser(req, res) {

    const { name, email= req.body.email.trim().toLowerCase(), password } = req.body;/*here we are destructuring the 
    name, email and password from the request body for clean code and also we 
     intentionally lowercased the email*/

    if (!name || !name.trim() || !email || !password) {/*here we are using trim() method to remove 
        whitespace from both ends of a string and check if the name is 
        empty or not*/

        return res.status(400).json({
            success: false,
            message: "Name, Email and Password are required"
        });
    }

    const existingUser = await User.findOne({
     email: email/*here we are checking if the email already exists in 
    the mongo database using the findOne method of the User model*/
    });

    if (existingUser) {

        return res.status(400).json({
            success: false,
            message: "Email already exists"
        });
    }
    /*here we are  hasing the password using bcrypt and store them as haspasswords
    and one more thing in bcrypt there is no encryptingand decryptimg it will
    directly verify the plain text password with the hashed password*/
    const hashedPassword = await bcrypt.hash(
        password,
        10/* 10 is the cost faactor the computational leevel of password hashing*/
    );
    
     /*here we are denoting the contentss that have to extarcted from user details 
    this technique  of denoting onnlly thee required details and accepting them is called
    as whitelisting */
    /*Whitelisting means explicitly specifying which input fields are allowed and ignoring 
    (or rejecting) everything else.*/
    const newUser = {
        name: name.trim(),/*here we are using trim() method to remove
        whitespace from both ends of a string and check if the 
        ame is empty or not*/
        email: email.trim(),/*here we are using trim() method to remove
        whitespace from both ends of a string and check if the 
        email is empty or not*/
        password: hashedPassword,
        role: "user"
    };

    const createdUser = await User.create(newUser);/*here wee replaced users.push(newUser)
     with User.create(newUser) to store the new user in the database
     and also returning the created user as it will return with id generated
     by MongoDB*/

    return res.status(201).json({
        success: true,
        message: "User Registered Successfully",
        user: {
        id: createdUser._id,
        name: createdUser.name,
        email: createdUser.email,
        role: createdUser.role
    }/*heere we are returning the created user details in the response and 
    also returning the id generated by MongoDB and we are defining what to show coz
    we don't want to return the hashed password*/
    });

}

    /* ===========================
   Login User
=========================== */
async function loginUser(req, res) {

    const { email= req.body.email.trim().toLowerCase(), password } = req.body;/*here we are destructuring the
     email and password from the request body for clean code and also we 
     intentionally lowercased the email*/

    const user = await User.findOne({
        email: email/*here we are finding the user by email using 
        the findOne method of the User model*/
        /*findone will return the first document that matches the query 
        and if no document is found, it will return null*/
    });

    if (!user) {/*!user is denoting not equalto*/


        return res.status(400).json({
            success: false,
            message: "User not found"
        });

    }
    /*here we are comparing the hashed password using with user entered password 
    using bcrypt.compare()*/
    const isMatch = await bcrypt.compare(
        password,
        user.password
    );

    if (!isMatch) {
        return res.status(400).json({
            success: false,
            message: "Invalid Password"
        });

    }
     
    // Create payload
    const payload = {/*here we are creating a payload which will be 
        used to generate the token word payload is the data that will be encoded 
        in the token and it can be any data technical terms used in jwt are 
        payload, header and signature*/
        id: user._id,/*this _id is the unique identifier generated by 
        MongoDB for each document in the collection*/
        email: user.email,
        role: user.role
    };

    const token = jwt.sign(
        payload,
        process.env.JWT_SECRET,/*this is the secret key used to sign the token 
        and it should be kept secret and not be shared with anyone
        we will replace this with an environment variable in production 
        later*/
        {
           expiresIn: "2h"/*expires in is a optionIt limits the lifetime of a JWT. 
           If a token is stolen, it cannot be used forever because it automatically
            becomes invalid after the configured time*/
        }/*here we are setting the expiration time for the token to 2 hours
    for safety and security reasons and it can be set to any time limit
     as per the requirement*/
    ); /*typical jwt sign format is jwt.sign(payload, secretOrPrivateKey, 
    [options, callback])*/

    return res.status(200).json({
        success: true,
        message: "Login Successful",
        token: token
    });

}

/*here we are creating the controller functions for the user module
and exporting them for use in the routes using module.exports 
like joblib in python*/
async function   getUsers(req, res) {
    try {/*here we used pagionation to send 10 users per page
         as showing all the users in single page is bit risky*/
        const users = await User.find()
               .select("-password")
               .skip(0)
               .limit(10);/*here we are finding all the users 
        using the find method of the User model*/
        /*and also we are nto sending the hashed password as it is confidential 
        select("-password") will explicit the password and send other details as response*/
        return res.status(200).json({
            success: true,
            users
        });
    } catch (error) {
        return res.status(500).json({
            success: false,
            message: "Internal Server Error"
        });
    }
}

/*here we are creating a function to update user details and it will be used
by the admin and the user itself to update their details*/
const updateUser = async (req, res) => {
    try {
        const userId = req.params.id;

        // 1. Validate MongoDB ObjectId
        if (!mongoose.Types.ObjectId.isValid(userId)) {
            return res.status(400).json({
                success: false,
                message: "Invalid User ID"
            });
        }

        // 2. Authorization check
        // Admin can update anyone.
        // Normal user can update only their own account.
        if (
            req.user.role !== "admin" &&
            req.user.id !== userId
        ) {
            return res.status(403).json({
                success: false,
                message: "Access Denied"
            });
        }

        // 3. Find the user
        const user = await User.findById(userId);

        if (!user) {
            return res.status(404).json({
                success: false,
                message: "User Not Found"
            });
        }

        // 4. Create an object containing ONLY allowed fields
        const updateData = {};

        if (req.body.name !== undefined) {
            updateData.name = req.body.name.trim();
        }

        // 5. Handle email update
        if (req.body.email !== undefined) {
            const normalizedEmail = req.body.email
                .trim()
                .toLowerCase();/*here we are normalizing the email using 
                trim and tolowercase*/

            // Check whether another user already has this email
            const existingUser = await User.findOne({
                email: normalizedEmail,
                _id: { $ne: userId }
            });/*$ne means "not equal". Find a user with this email whose _id is
             not the user currently being updated.*/

            if (existingUser) {
                return res.status(400).json({
                    success: false,
                    message: "Email already exists"
                });
            }

            updateData.email = normalizedEmail;
        }

        // 6. Handle password update
        if (req.body.password !== undefined) {
            updateData.password = await bcrypt.hash(
                req.body.password,
                10
            );
        }

        // 7. Update the user
        const updatedUser = await User.findByIdAndUpdate(
            userId,
            updateData,
            {/* new, runValidators are options provided by Mongoose.*/
                new: true,/*shows the new updated object instead of before update 
                object*/
                runValidators: true /*tells Mongoose to apply the schema validation 
                rules when performing the update*/
            }
        ).select("-password");/*excluding the password */

        // 8. Send response
        return res.status(200).json({
            success: true,
            message: "User updated successfully",
            user: updatedUser
        });

    } catch (error) {

        // Log the actual error on the server
        console.error("Update User Error:", error);

        // Send a safe error message to the client
        return res.status(500).json({
            success: false,
            message: "Internal Server Error"
        });
    }
};

//*
 * This function allows an admin or the user themselves
 * to delete a user account.
 */
async function deleteUser(req, res) {

    try {

        // Get the MongoDB document ID from the URL.
        // MongoDB uses ObjectId for document IDs, and
        // req.params.id is received as a string.
        const userId = req.params.id;


        // 1. Validate the MongoDB ObjectId.
        // This prevents Mongoose CastError for invalid IDs.
        if (!mongoose.Types.ObjectId.isValid(userId)) {

            return res.status(400).json({
                success: false,
                message: "Invalid User ID"
            });

        }


        // 2. Authorization check.
        //
        // Admins can delete any user.
        // A normal user can delete only their own account.
        //
        // req.user.id comes from the JWT payload.
        // req.user.role comes from the JWT payload.
        if (
            req.user.role !== "admin" &&
            req.user.id !== userId
        ) {

            return res.status(403).json({
                success: false,
                message: "Access Denied"
            });

        }


        // 3. Find and delete the user in ONE database operation.
        //
        // findByIdAndDelete() returns the deleted document
        // if the user exists.
        //
        // If no user exists with this ID, it returns null.
        const deletedUser = await User.findByIdAndDelete(userId);


        // 4. Valid ObjectId, but no user was found.
        if (!deletedUser) {

            return res.status(404).json({
                success: false,
                message: "User Not Found"
            });

        }


        // 5. User successfully deleted.
        return res.status(200).json({
            success: true,
            message: "User deleted successfully"
        });

    } catch (error) {

        // Log the actual error on the server.
        console.error("Delete User Error:", error);


        // Don't expose internal database/server errors
        // to the client.
        return res.status(500).json({
            success: false,
            message: "Internal Server Error"
        });

    }
}

/*here we are creating a function to promote a user to admin role*/
async function promoteUser(req, res) {

    const userId = req.params.id;/*here we changed the number conversion to 
    string as MongoDB generates unique string IDs for each document*/

    const user = await User.findById(userId);/*here we are finding the user by 
    id using the findById method of the User model*/

    if (!user) {

        return res.status(404).json({
            success: false,
            message: "User Not Found"
        });

    }
    
    if (user.role === "admin") {

    return res.status(400).json({
        success: false,
        message: "User is already an admin"
    });

}     


    user.role = "admin";

    await user.save();/*this line stores the updated user details in the 
    database using the save method of the User model*/

    return res.json({
        success: true,
        message: "User promoted successfully"
    });

}

module.exports = {
    getUsers,
    registerUser,
    loginUser,
    promoteUser,
    updateUser, 
    deleteUser
};
