#this file is a Kubernetes Secret manifest that defines a Secret named backend-secret. A Secret is an API object used to store 
#sensitive data, such as passwords, OAuth tokens, and SSH keys. In this case, the Secret contains a single key-value pair: JWT_SECRET. The JWT_SECRET key holds a secret value that will be used by the backend application to sign and verify JSON Web Tokens (JWTs) for authentication and authorization purposes. This Secret can be mounted as an environment variable or a file in a pod, allowing the backend application to access the secret value securely at runtime.

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  JWT_SECRET: docker-development-secret #this is the secret value that will be used by the backend application to sign and verify JSON Web Tokens (JWTs) for authentication and authorization purposes. It is stored in the Secret as a key-value pair, where the key is JWT_SECRET and the value is docker-development-secret. This secret value can be accessed securely by the backend application at runtime, either as an environment variable or a file mounted in the pod.