apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort #nodeport is a type of service that exposes the service on each node's IP at a static port (the NodePort). A ClusterIP service, to which the NodePort service routes, is automatically created. You’ll be able to contact the NodePort service, from outside the cluster, by requesting <NodeIP>:<NodePort>.

  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 80 #target port is the port on the pod that the service should forward traffic to. In this case, it is set to 80, which is the port that the frontend container is listening on.
      nodePort: 30080 #this port will be used to access the service from outside the cluster. It is a static port that will be exposed on each node in the cluster, allowing external traffic to reach the frontend service.