apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo #this selector will match the label of the pods created by the mongo deployment, allowing the service to route traffic to those pods

  ports:
    - port: 27017 #this is the port that the service will expose to the outside world, allowing clients to connect to the MongoDB database through this port
      targetPort: 27017 #targetPort specifies the port on the pod that the service should forward traffic to, which in this case is the default MongoDB port 27017