apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce #readwriteonce means that the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi #requests specifies the minimum storage required for the volume