/*is a TypeScript declaration file specifically used by Vite projects.*/
/*when you create a new Vite project with TypeScript, this file is automatically generated in the src directory.*/
/*and also it helps TypeScript to understand the types of Vite-specific features and APIs that are available in 
the project.*/
/*it makes typescript to understand css and other files that are imported in the project which avoids type errors
.*/

/// <reference types="vite/client" />